---
services:
  app:
    image: snipe/snipe-it:v4.1.13
    container_name: snipe-it-app
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    volumes:
      - ./snipeit:/var/lib/snipeit
    env_file:
      - .env

  mysql:
    image: mysql:5.6
    container_name: snipe-it-mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
